### ISSUE TITLE
Search and trees for various finders

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/curatron#11]
Curators should be able to use Excel. We can do various validation inside Excel, but we can't include large ontologies. So I think the curators will need web pages where they can quickly look up the terms they need. I think we have everything we need with Gizmos search and tree functionality. We will need pages for:

1. organisms (down to species level)
2. subspecies
3. proteins
4. non-peptides
5. molecules
6. assays (divide into bcell, tcell, mhc?)
7. diseases
8. geolocations

... I've probably misses some, but I think these are the most important ones, listed in order of importance.

This will come from the OWL files built by Arborist and intended for the curation system.

This will also support #8.

**Comment by beckyjackson** [comment]
Should this be a CGI script for DROID, or a standalone Flask app?

**Comment by jamesaoverton** [comment]
I’d prefer Flask with the CGI option used here https://github.com/ontodev/sprocket/blob/main/sprocket/run.py#L691

**Comment by jamesaoverton** [comment]
Resolved by #12
